// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHILZL11q4YWXTuATYnmPyk10amqE6Sfs',
    appId: '1:1071386885521:web:adcbf4f0d11104ce4c2e30',
    messagingSenderId: '1071386885521',
    projectId: 'livestreamingapp-eafc0',
    authDomain: 'livestreamingapp-eafc0.firebaseapp.com',
    storageBucket: 'livestreamingapp-eafc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLUrBYA-lLHDDeti5TntLfO30wYuCYVM',
    appId: '1:1071386885521:android:e98e6f345668acd34c2e30',
    messagingSenderId: '1071386885521',
    projectId: 'livestreamingapp-eafc0',
    storageBucket: 'livestreamingapp-eafc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQHILfd_fwTiuNyOTFXBGbW98SGKbbTZU',
    appId: '1:1071386885521:ios:6e61feed797396dd4c2e30',
    messagingSenderId: '1071386885521',
    projectId: 'livestreamingapp-eafc0',
    storageBucket: 'livestreamingapp-eafc0.appspot.com',
    iosBundleId: 'com.example.livestreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQHILfd_fwTiuNyOTFXBGbW98SGKbbTZU',
    appId: '1:1071386885521:ios:6e61feed797396dd4c2e30',
    messagingSenderId: '1071386885521',
    projectId: 'livestreamingapp-eafc0',
    storageBucket: 'livestreamingapp-eafc0.appspot.com',
    iosBundleId: 'com.example.livestreaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHILZL11q4YWXTuATYnmPyk10amqE6Sfs',
    appId: '1:1071386885521:web:43f8f0fcc21d53044c2e30',
    messagingSenderId: '1071386885521',
    projectId: 'livestreamingapp-eafc0',
    authDomain: 'livestreamingapp-eafc0.firebaseapp.com',
    storageBucket: 'livestreamingapp-eafc0.appspot.com',
  );
}
